name: Go Lint

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Install linter
      run: |
        go get -u golang.org/x/lint/golint

    - name: Run linting checks
      run: |
        golint ./...
